backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: home
    label: Homepage
    files:
      - name: homeContent                 # <-- required
        file: "src/content/home.json"
        label: "Homepage Content"
        fields:
          - { name: heroTitle, label: "Hero Title", widget: string }
          - { name: heroSubtitle, label: "Hero Subtitle", widget: text }
          - { name: finalCtaTitle, label: "Final CTA Title", widget: string, required: false }
          - { name: finalCtaSubtitle, label: "Final CTA Subtitle", widget: text, required: false }

  - name: contact
    label: "Contact Page"
    files:
      - name: contactContent              # <-- required
        file: "src/content/contact.json"
        label: "Contact Page"
        fields:
          - { name: headline, label: "Headline", widget: string }
          - { name: subheadline, label: "Subheadline", widget: text }
          - { name: bannerSuccess, label: "Success Banner", widget: text, required: false }
          - { name: bannerError, label: "Error Banner", widget: text, required: false }
  - label: "Site Settings"
    name: "site"
    files:
      - label: "Global"
        name: "global"
        file: "src/content/cms/site.json"
        fields:
          - { label: "Brand Name", name: "brandName", widget: "string" }
          - { label: "Email", name: "email", widget: "string", pattern: [".+@.+\\..+", "Invalid email"] }
          - { label: "Phone (raw, human)", name: "phoneRaw", widget: "string", hint: "e.g. +30 69X XXX XXXX" }
          - { label: "WhatsApp default message", name: "whatsappDefaultMsg", widget: "string", required: false }
          - { label: "Booking URL", name: "booking", widget: "string" }
          - { label: "Airbnb URL", name: "airbnb", widget: "string" }
          - { label: "Instagram URL", name: "instagram", widget: "string", required: false }
          - { label: "Facebook URL", name: "facebook", widget: "string", required: false }
