backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "apartment"
    label: "Apartments"
    folder: "src/content/apartment"
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    fields:
      - { name: title, label: Title }
      - { name: slug, label: Slug }
      - { name: description, label: Description, widget: text }
      - { name: heroImage, label: Hero Image, widget: image }
      - name: gallery
        label: Gallery
        widget: list
        field: { name: image, label: Image, widget: image }
      - { name: amenities, label: Amenities, widget: list }
      - name: seo
        label: SEO
        widget: object
        collapsed: true
        fields:
          - { name: title, label: SEO Title }
          - { name: description, label: SEO Description, widget: text }
          - { name: canonical, label: Canonical URL, required: false }
      - { name: published, label: Published, widget: boolean, default: true }
      - { name: order, label: Order, widget: number, default: 0 }
